### ISSUE TITLE
Building fails with AndroidBuildTools 19

### ISSUE THREAD

**Issue by NiciDieNase** [kony/HelloWorld#1]
When trying to build this with Kony Studio and Android Build Tools v19 I got a BufferOverflowException.

According to this Stackoverflow-Post I downgraded to v18 which fixed the problem: http://stackoverflow.com/questions/19727915/android-dex-gives-a-bufferoverflowexception

**Comment by rakeshts** [comment]
This looks like an ANT error, which might happen for the following reasons 
1. Ant file missing
2. Ant file not mapped against the environmental variables

try coping the ant file to your kony installable

**Comment by bhargavib** [comment]
This is issue in android build tools 19 . Upgrade to next version of build tools (>19) or downgrade to version 18.

https://code.google.com/p/android/issues/detail?id=61710

Thanks
Bhargavi B

On Feb 10, 2014, at 2:21 AM, "Rakesh" <notifications@github.com<mailto:notifications@github.com>> wrote:

This looks like an ANT error, which might happen for the following reasons
1. Ant file missing
2. Ant file not mapped against the environmental variables

try coping the ant file to your kony installable

##
