### ISSUE TITLE
Preview issue on VSZ 7

### ISSUE THREAD

**Issue by Jhtang** [kony/HelloWorld#2]
I imported it to VSZ 7.
I tried to run it in Preview mode for iOS and Android. Both failed to run.
![screen shot 2016-05-19 at 4 11 31 pm](https://cloud.githubusercontent.com/assets/489098/15408085/671671de-1ddc-11e6-9c58-ba97c8843268.png)
![screen shot 2016-05-19 at 4 14 25 pm](https://cloud.githubusercontent.com/assets/489098/15408176/c96c85f8-1ddc-11e6-9515-9d96b34381ac.png)

**Comment by KonyDev** [comment]
Sorry for the inconvenience caused.The application is updated now,can you please check with the latest build.
